### ISSUE TITLE
async api?

### ISSUE THREAD

**Issue by slorber** [expo/react-native-action-sheet#100]
Hi,

Would it be possible to provide an async/promise based api, so that calling showActionSheet will resolve only when action sheet is dismissed?

I've done this already with Alert.alert() of RN, just wonder if you'd be interested to have the same in this lib. This would be handy for my apps where I want to chain an actionsheet question inside an existing async flow, without going back and forth from promises to callbacks which is quite error-prone and can lead to promises never resolving.

https://github.com/slorber/react-native-alert-async

**Comment by SimenB** [comment]
I do

```tsx
new Promise<number>(resolve => {
  showActionSheetWithOptions(
    { options: addReceiptPromptOptions, cancelButtonIndex: 2 },
    resolve,
  );
});
```
which works fine and isn't too much code

**Comment by bradbumbalough** [comment]
Closing this since a valid work around was provided.

**Comment by SimenB** [comment]
(to be clear, I think the callback api should be dropped in favour of a promise based one, but it's no biggie 🙂)
