### ISSUE TITLE
Allow dismissing ActionSheet

### ISSUE THREAD

**Issue by GabrielePrestifilippo** [expo/react-native-action-sheet#104]
### Introduction

The current implementation of ActionSheetIOS (even after #103) does not support a way to destroy the current ActionSheet programmatically. Therefore, the only way to dismiss it is to tap on one of the options. 

### The Core of It

As of now, it is also possible to open multiple ActionSheets, appearing one on top of another. This results in odd behaviors. There should be only one ActionSheet at any time.

A better implementation would support a way to dismiss an opened ActionSheet.

I hence propose two possible solutions, depending if we want to keep multiple ActionSheets or just one.

1. Forcing to have at most one ActionSheet opened at any time and creating a method `dismiss()` which would destroy the current ActionSheet.

2. Support multiple ActionSheets and create a method `dismissLast()` which would destroy the last ActionSheet and a method `dismissAll()` to destroy all of them.

### Discussion points

I prefer the first option by forcing one ActionSheet at a time and creating the method `dismiss()`.
However, iOS does not specify if it's possible to have multiple ones in the [guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/views/action-sheets/), so I leave the discussion open to that possibility. 

I can open a pull request implementing this feature, however, I would like to wait for some feedback from your side.

**Comment by outaTiME** [comment]
@brentvatne what do you think about that? 
it will be great to have this option for better control over action sheet.

**Comment by brentvatne** [comment]
up to @bradbumbalough! he leads this project

**Comment by bradbumbalough** [comment]
This should be straightforward enough for Android since we control the implementation, but since there's not an existing API to dismiss an iOS action sheet we'll need to handle that differently... without the ability to add a native method to dismiss it from the Objective-C side.

@outaTiME what use case are you envisioning that would benefit from this feature?

**Comment by mbret** [comment]
I think the use case is a conveniant user experience for dismissing the action sheet. Most of the action sheets on android can be dismissed by clicking outside of it, this is an expected behavior for the user.
