### ISSUE TITLE
Clarification for "on web" in README

### ISSUE THREAD

**Issue by bugs181** [expo/react-native-action-sheet#107]
In the README, it states:

> This library can also be used with on web with Expo.

I'm coming from the assumption that Expo is a React Native only platform. Where/how does one run Expo on the web? Citation needed. If talking about `react-native-web` project, then that is not Expo specific.

**Comment by SimenB** [comment]
https://blog.expo.io/expo-cli-and-sdk-web-support-beta-d0c588221375
