### ISSUE TITLE
Android: Calling showActionSheetWithOptions from an action sheet selection results in a NOOP

### ISSUE THREAD

**Issue by dozoisch** [expo/react-native-action-sheet#112]
If on select of an action sheet option you call another showActionSheetWithOptions nothing happens on android due to [isVisible](https://github.com/expo/react-native-action-sheet/blob/master/ActionSheet.js#L307) being true at the time. isVisible is only set to false after ~225ms which is the animation timing, which is before the onSelect is called. On iOS it properly pops the second sheet.

The only work around right now is to "save" the callback and call it within the onAnimationOut.

**Comment by jhogervorst** [comment]
Example workaround:

```diff
	import React from "react";
+	import { Platform } from "react-native";
	import { connectActionSheet } from "@expo/react-native-action-sheet";

	class MyComponent extends React.Component {
+		// @expo/react-native-action-sheet does not support showing a new action
+		// sheet from an existing visible action sheet
+		// https://github.com/expo/react-native-action-sheet/issues/112
+		onAnimateOut = () => {
+			this.nextActionSheet && this.nextActionSheet();
+			this.nextActionSheet = null;
+		};
+		showNextActionSheet = (next) => {
+			if (Platform.OS === "ios") {
+				next();
+			} else {
+				this.nextActionSheet = next;
+			}
+		};

		showAction = () => {
			this.props.showActionSheetWithOptions(
				{ options: ["Show Other Action"] },
-				this.showOtherAction,
+				() => this.showNextActionSheet(this.showOtherAction),
+				this.onAnimateOut,
			);
		};

		showOtherAction = () => {
			this.props.showActionSheetWithOptions(
				// ...
			);
		};
	}
```

1. Add the methods `onAnimateOut` and `showNextActionSheet`;
2. Replace your onSelect call with `() => this.showNextActionSheet(...)` (passing in a function that shows the next action sheet); and
3. Add `this.onAnimateOut` as third parameter to `showActionSheetWithOptions` (only required for action sheets that open a next action sheet).

**Comment by ouabing** [comment]
Well I don't find the `onAnimateOut` callback in the latest version...

**Comment by bradbumbalough** [comment]
@ouabing I'm having the same issue too.. here's my workaround: 

```js
  showNextActionSheet = next => {
    if (Constants.platform.ios) {
      next();
    } else {
      delay(next, 200);
    }
  };
```
Using lodash's `delay` method, but `setTimeout` would work too. According to https://github.com/expo/react-native-action-sheet/blob/dc2176e463a8ef00a8d97f38400e90669e12e7cc/src/ActionSheet/index.tsx#L27 it takes `195` ms to animate out.

**Comment by bradbumbalough** [comment]
Released in 3.2.0.

**Comment by dozoisch** [comment]
@bradbumbalough seems like this is still a bug in 3.2.0 https://snack.expo.io/@bradbumbalough/thoughtful-waffles and the snack doesn't work on android.


Changing 

```
selectedIndex => {
        if (selectedIndex === 0) {
          count.current = count.current + 1;
          openOptions();
        }
      }
```

to this: 

```
selectedIndex => {
        if (selectedIndex === 0) {
          count.current = count.current + 1;
          setTimeout(() => openOptions(), 0);
        }
      }
```

makes it work again. 

This is due to the onSelect happening before the animate out here https://github.com/expo/react-native-action-sheet/blob/master/src/ActionSheet/index.tsx#L209

**Comment by bradbumbalough** [comment]
@dozoisch thanks for pointing this out! You're right -- there seems to be some inconsistencies with this API. I'm wondering if it's a race condition that allows it to work sometimes. I was able to get it working locally, but am also seeing it not work on the Snack and on an app consuming this version. I'll play with it and see if there's a better way to invoke it without the consumer needing to use `setTimeout`.

**Comment by dozoisch** [comment]
@bradbumbalough I think that we could set a property like "this._isSelectingOptions" before the onSelect. And then setting it back to false after it finished animating. This might be safer than using the state.

**Comment by bradbumbalough** [comment]
I think it might be because the defer code is looking for `isVisible && isAnimating` (https://github.com/expo/react-native-action-sheet/blob/master/src/ActionSheet/index.tsx#L143). It should probably work if it's just `isVisible` (as in, there's already an instance running).

**Comment by dozoisch** [comment]
Ah yep, just isVisible seems a lot safer.

**Comment by bradbumbalough** [comment]
I'm going to try it out locally...

**Comment by bradbumbalough** [comment]
@dozoisch care to take a peak at #140?

**Comment by bradbumbalough** [comment]
@dozoisch Ok this should be all set now in `3.3.2`.

**Comment by dozoisch** [comment]
@bradbumbalough confirmed it works =) thank you
