### ISSUE TITLE
Pass refs through connectActionSheet to child components

### ISSUE THREAD

**Issue by ahansson89** [expo/react-native-action-sheet#115]
I am trying to pass a ref through connectActionSheet to the child component without success.

Getting the following error: "Warning: Stateless function components cannot be given refs. Attempts to access this ref will fail."

**Comment by ahansson89** [comment]
Seems like it has been fixed here: https://github.com/ouabing/react-native-action-sheet/commit/83c28260c61d85721844b46b75a756241e19616a

Can we merge this commit in?

**Comment by bradbumbalough** [comment]
@ahansson89 is this still an issue? I seem to be able to pass a ref onto my connected action sheet now. Thanks!
