### ISSUE TITLE
Android only options should noop rather than error on iOS

### ISSUE THREAD

**Issue by brentvatne** [expo/react-native-action-sheet#118]

**Comment by bradbumbalough** [comment]
@brentvatne was this an error you experienced or just a precaution? I was looking into this issue but couldn't seem to replicate it in an iOS simulator. Thanks!

**Comment by brentvatne** [comment]
hey @bradbumbalough!

i found that if i tried to use any of the android-only options in the example app it would result in an error:

https://github.com/expo/react-native-action-sheet/blob/4e3914df1bfdb9c8a5ef3e431b66cfaefe131322/example/App.tsx#L66-L97

**Comment by bradbumbalough** [comment]
This was fixed in #144 and released in `3.4.1`.
