### ISSUE TITLE
simple changelog

### ISSUE THREAD

**Issue by sibelius** [expo/react-native-action-sheet#143]
can we keep a simple changelog?

like what are the breaking changes from v1 to v2 and from v2 to v3?

**Comment by bradbumbalough** [comment]
Thanks for the feedback @sibelius. I have an automated changelog in the works but haven't gotten it wired in, yet. Do you have a specific use case from prior versions you're concerned about or just noting this should be in place going forward? Thanks!

**Comment by sibelius** [comment]
go forward
