### ISSUE TITLE
Get wrapped component ref

### ISSUE THREAD

**Issue by mirhat** [expo/react-native-action-sheet#145]
How can I get reference to wrapped component?

**Comment by bradbumbalough** [comment]
Hi @mirhat! Could you provide your use case for needing the ref? Thanks.

**Comment by mirhat** [comment]
I wanted to create ActionSheet component that will be wrapped and use it my app when needed, wihout having to wrap every component in which I need showActionSheetWithOptions.
I have solved it by passing onRef function as param and return this from component.

`import { Component } from 'react'
import { connectActionSheet } from '@expo/react-native-action-sheet'
import AttachmentPicker from 'App/Utils/attachmentPicker'
import { PropTypes } from 'prop-types'

class ActionSheet extends Component {
  constructor(props) {
    super(props)
    this.pick = this.pick.bind(this)
    this.picker = new AttachmentPicker({ ...props, show: props.showActionSheetWithOptions })
  }
  componentDidMount() {
    this.props.onRef(this)
  }
  async pick(options) {
    const result = await this.picker.pick(options)
    return result
  }
  render() {
    return null
  }
}

ActionSheet.propTypes = {
  onRef: PropTypes.func,
  showActionSheetWithOptions: PropTypes.func,
}

const ConnectedActionSheet = connectActionSheet(ActionSheet)

export default ConnectedActionSheet
`
