### ISSUE TITLE
not working in dark mode

### ISSUE THREAD

**Issue by mi-mazouz** [expo/react-native-action-sheet#149]
Hi is there a way to avoid this in dark mode?
<img width="371" alt="Screen Shot 2019-12-16 at 5 45 19 PM" src="https://user-images.githubusercontent.com/24244248/70949462-dce68980-202b-11ea-96c0-9309d4ea669b.png">

**Comment by bradbumbalough** [comment]
Hey @mi-mazouz! This is what it looks like for me... can you provide some specs on what you're testing this on? iOS just invokes the native apis, so there's not a way to "handle" dark mode for it.
<img width="366" alt="Screen Shot 2019-12-17 at 11 20 46 AM" src="https://user-images.githubusercontent.com/9825605/71019172-832f9f00-20bf-11ea-9183-4a1620479b47.png">

**Comment by mi-mazouz** [comment]
here some code:

my component.tsx
```
<ActionSheet
    callbacksByIndex={[
        (): void => {
            handleCamaera((image) => { onProfilePictureChange(image.uri); });
        },
        (): void => {
            handleCamaeraRoll((image) => { onProfilePictureChange(image.uri); });
        },
    ]}
    options={['Take a photo', 'Choose from library', 'Cancel']}>
    <Avatar
        ImageComponent={(): React.ReactElement => (
            <ImageBackground
                source={myAvatar}
                // Throw error if any style is passed
                style={{}}>
                <View>
                    <Image source={require('../assets/camera_icon.png')} />
                </View>
            </ImageBackground>
        )} />
</ActionSheet>
```

ActionSheet.tsx
```
import { useActionSheet } from '@expo/react-native-action-sheet';
import React, { ReactElement } from 'react';
import { TouchableOpacity, TouchableOpacityProps } from 'react-native';

interface Props extends TouchableOpacityProps {
    callbacksByIndex: Array<() => void>;
    children: ReactElement;
    options: string[];
}

const ActionSheet = ({
    children, options, callbacksByIndex, ...props
}: Props): ReactElement => {
    const { showActionSheetWithOptions } = useActionSheet();

    const onOpenActionSheet = (): void => {
        const cancelButtonIndex = options.length - 1;

        showActionSheetWithOptions(
            {
                cancelButtonIndex,
                options,
                tintColor: 'blue',
            },
            (buttonIndex) => {
                if (typeof callbacksByIndex[buttonIndex] === 'function') {
                    callbacksByIndex[buttonIndex]();
                }
            },
        );
    };

    return (
        <TouchableOpacity {...props} onPress={onOpenActionSheet}>
            {children}
        </TouchableOpacity>
    );
};

export default ActionSheet;

```

**Comment by bradbumbalough** [comment]
What happens if you remove the `tintColor` option?

**Comment by mi-mazouz** [comment]
@bradbumbalough thanks it's working!!

**Comment by outaTiME** [comment]
No dark mode support on android =( any feature for that ?

this is how looks like:

<img width="668" alt="image" src="https://user-images.githubusercontent.com/140472/78099286-cf28fa00-73b7-11ea-9b11-95038bc1fcb8.png">

**Comment by bradbumbalough** [comment]
@outaTiME correct it's not supported out of box, however, you are able to override the default styles for Android to make it work in your case. https://github.com/expo/react-native-action-sheet#containerstyle-optional.

**Comment by outaTiME** [comment]
thanks @bradbumbalough i made a customization and works flawlessly 🎉

**Comment by downtowndev** [comment]
@bradbumbalough How is dark mode enabled for the ActionSheet on iOS? I set my device to dark mode, but the ActionSheet still shows up with light buttons, and I don't see any config options listed for iOS to change the button colors. Based on the first two images on this ticket though, it looks like it's possible?

**Comment by bradbumbalough** [comment]
@downtowndev if you're in a managed expo app I think you have to opt into the color modes... https://docs.expo.io/versions/v38.0.0/sdk/appearance/.

**Comment by downtowndev** [comment]
@bradbumbalough Neat, that did the trick. Thanks!
