### ISSUE TITLE
[Android] Unsupported node type: transform

### ISSUE THREAD

**Issue by kfiroo** [expo/react-native-action-sheet#15]
Hey,

I'm getting the following error when trying to open the action sheet:
![image](https://cloud.githubusercontent.com/assets/284636/17837729/c49f2824-67c3-11e6-90fe-99df07ecee2f.png)

Looks like checking for `NativeModules.NativeAnimatedModule` in this [commit](https://github.com/exponentjs/react-native-action-sheet/commit/8e879d734517eff21603643f35b2a945036fc781) is not enough because we are using `transform` which it not supported yet in RN.

This commit from Aug 7, 2016 https://github.com/facebook/react-native/commit/df053117778d8ebcc1943f20127e49078f79da0b will introduce `transform` support but it will only be released with RN v0.33.0

I'm using a forked version that sets the `useNativeDriver=false` for now :(

**Comment by FaridSafi** [comment]
+1

**Comment by JonasWho** [comment]
+1

**Comment by kfiroo** [comment]
@brentvatne Any updates on this?

**Comment by brentvatne** [comment]
@kfiroo - I think it's best to use the forked version given that this is solved in v0.33.0 and is a much better way of doing the animation. If you want to submit a pull request to make it optional to disable the native driver, I'd be open to that also :)

**Comment by kfiroo** [comment]
@brentvatne https://github.com/exponentjs/react-native-action-sheet/pull/19 this should work for now

**Comment by shaneosullivan** [comment]
I ran into this too, and had to google around for this fix - can we updated the readme to have the default docs say to use the new useNativeDriver={false} prop?

**Comment by brentvatne** [comment]
@shaneosullivan - sure, would accept a PR for that
