### ISSUE TITLE
[iOS] Is it possible to add numberOfLines option?

### ISSUE THREAD

**Issue by MaxInMoon** [expo/react-native-action-sheet#153]
On iOS, it is only possible to render option on 1 line.

Is there a way to render it on two lines, like here:
https://stackoverflow.com/a/42865424/5832547

Thank you

**Comment by amauryfischer** [comment]
We also need this feature in our project, is there a way to do it ?

**Comment by bradbumbalough** [comment]
Hi @MaxInMoon and @amauryfischer. For iOS, this repo just defers to `ActionSheetIOS` (see https://github.com/expo/react-native-action-sheet/blob/master/src/ActionSheet/index.ios.tsx), so this would have to be first supported at the RN level before it could be exposed here.
