### ISSUE TITLE
[Android]TypeError: Super expression must either be null or a function in react-native@0.62.0-rc.5

### ISSUE THREAD

**Issue by SunskyXH** [expo/react-native-action-sheet#161]
Description:

- the error happens while running `react-native run-android` after upgrade from `0.61.5` to `0.62.0-rc.5`.
- this upgrade change is according to https://react-native-community.github.io/upgrade-helper
- screenshot here, and I see `TouchableNativeFeedbackSafe` in the error stack, and I found it was invoked by `ActionSheetProvider`

<details>
<summary>screenshot</summary>

![image](https://user-images.githubusercontent.com/10584186/76731137-a38ef880-6797-11ea-865b-ea7ef1019189.png)

</details>

React Native version:

<details>
<summary>react-native info outputs</summary>

```
  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
    Memory: 252.58 MB / 16.00 GB
    Shell: 2.7.1 - /usr/local/bin/fish
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.22.4 - ~/.yarn/bin/yarn
    npm: 6.10.3 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 28, 29
      Build Tools: 28.0.3, 29.0.2
      System Images: android-25 | Google APIs ARM EABI v7a, android-29 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 3.6 AI-192.7142.36.36.6241897
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    @react-native-community/cli: ^4.3.0 => 4.3.0 
    react: 16.13.0 => 16.13.0 
    react-native: 0.62.0-rc.5 => 0.62.0-rc.5 
  npmGlobalPackages:
    *react-native*: Not Found
```

</details>

## Steps To Reproduce

1. change my codes according to https://react-native-community.github.io/upgrade-helper.
2. run `react-native run-ios`, and it is OK.
3. run `react-native run-android` and then meet this error. 
4. I just created a new project with react-native@0.62.0-rc.5 and @expo/react-native-action-sheet@3.5.0, the problem can reproduce, here is the [link](https://github.com/SunskyXH/ActionSheetTest)

## Expected Results

1. successfully run the android app.

**Comment by wong2** [comment]
I'm blocked by this issue too

**Comment by wong2** [comment]
any updates?

**Comment by shivaping** [comment]
Any update on this ? we are stuck post RN62 update

**Comment by Thomazella** [comment]
Also stuck in this

**Comment by bradbumbalough** [comment]
I'm sorry for the delay on this!

**Comment by betoharres** [comment]
Just in time, thanks a lot @bradbumbalough !!

**Comment by zhigang1992** [comment]
![image](https://user-images.githubusercontent.com/1057756/78751100-2c1e4480-79a4-11ea-8cc0-be64ebf57733.png)

I'm still seeing this with 3.6.0, was it not the same issue?

**Comment by Thomazella** [comment]
Did you try removing node modules and caches?

**Comment by zhigang1992** [comment]
no, but but the code is updated as per screenshot. I'll try that and report back.

**Comment by Thomazella** [comment]
Maybe it's not this library. What's that action group file in your stack trace?

**Comment by bradbumbalough** [comment]
ActionGroup is a component in the package. @zhigang1992 can you provide the package or yarn lock record for `@expo/react-native-action-sheet`?

**Comment by zhigang1992** [comment]
sry, it was https://github.com/FaridSafi/react-native-gifted-chat/issues/1703 after force resolution it's now working.

**Comment by Cattpot** [comment]
Hello, still have the problem with RN 62.2
Already updated to 3.6.0 and removed Cache, node_modules, gradleclean etc.
tried to comment the library out, no error then..

**Comment by Cattpot** [comment]
Hello, still have the problem with RN 62.2
Already updated to 3.6.0 and removed Cache, node_modules, gradleclean etc.
tried to comment the library out, no error then..

**Comment by bradbumbalough** [comment]
@Cattpot can you provide your package-lock or yarn-lock version for @expo/react-native-action-sheet?

**Comment by Cattpot** [comment]
`    "@expo/react-native-action-sheet": {
      "version": "3.6.0",
      "resolved": "https://registry.npmjs.org/@expo/react-native-action-sheet/-/react-native-action-sheet-3.6.0.tgz",
      "integrity": "sha512-sAxQZ57iGkn/nKHvJoj51KIvnVx9RdMTpk2lKlo3FKPaezLWsdK0P9zLI/xG3NrD6CRr9tt3oK0silYi61VvZA==",
      "requires": {
        "@types/hoist-non-react-statics": "^3.3.1",
        "hoist-non-react-statics": "^3.3.0"
      }
    },`

**Comment by Cattpot** [comment]
nvm, tried a new RN 62.2, it works
so it's a problem with my repo..

**Comment by amirduran** [comment]
@Cattpot I'm experiencing similar issue. What was exactly your problem?

**Comment by Cattpot** [comment]
> @Cattpot I'm experiencing similar issue. What was exactly your problem?

Actually, I dont know. I created a new 62.2 and then it worked..

**Comment by nasimkashefi** [comment]
I have the same problem. I have downloaded mStore project and need to run it. can't find the error root.
