### ISSUE TITLE
Pressing outside the action sheet only dismisses if a cancel index is provided and valid

### ISSUE THREAD

**Issue by kinigitbyday** [expo/react-native-action-sheet#173]
On iOS, it's possible to "dismiss" the action sheet by pressing outside of the sheet. However, this only seems to work if a `cancelButtonIndex` is provided, and is a valid index for the set of options. 

It might be by design, but there's a reasonable extension of this library to use it as a menu option selector. Doing so with a cancel option is a bit counterintuitive, but otherwise the sheet isn't dismissible.

**Comment by bradbumbalough** [comment]
Hey @nicknovitski, are you saying that this functions correctly in iOS but not in Android, or is broken in both OS's when a `cancelButtonIndex` is not provided?

**Comment by kinigitbyday** [comment]
I think you tagged the wrong person. 

But I haven't actually tried it in android, so I don't know what the behavior would be. I can give it a go if that would help.

**Comment by bradbumbalough** [comment]
Ah sorry. Ok so you're saying the issue is in iOS for you? The only issue is that this repo doesn't do any special handling for iOS, it just returns the ActionSheetIOS RN package. So this would then be an issue with the native package.

**Comment by kinigitbyday** [comment]
Got it, that makes sense. Thanks. Feel free to close this, then.
