### ISSUE TITLE
ActionSheetProvider in place, class actionSheet works, hook actionSheet does not work.

### ISSUE THREAD

**Issue by superandrew** [expo/react-native-action-sheet#181]
I have an ActionSheetProvider that works and is in App.tsx. In many class component the actionSheet works, however in a functional component using the hook it doesn't.

I was trying to make sure I followed correctly the docs.

App.tsx
![CleanShot 2020-08-16 at 14 51 18@2x](https://user-images.githubusercontent.com/71364/90334720-f92e3200-dfcf-11ea-9925-730822eca948.png)

In my functional component:

```

const { showActionSheetWithOptions } = useActionSheet();

const openActionSheet = (document: {}) =>
    showActionSheetWithOptions(
      {
        options,
        cancelButtonIndex,
      },
      (buttonIndex) => {
        switch (buttonIndex) {
          case 0:
            pickImageAsync(
              onDocumentPicker,
              document != null
                ? document
                : { document: { documentType: "foto" } }
            );
            return;
          case 1:
            takePictureAsync(
              onDocumentPicker,
              document != null
                ? {
                    document,
                  }
                : null
            );
            return;
          case 2:
            chooseFileAsync(
              onDocumentPicker,
              document != null
                ? {
                    document,
                  }
                : null
            );
            return;
          default:
        }
      }
    );
```

The action gets fired but nothing happens. Any help would be appreciated. Since the examples in the doc explain how to use the hook in app.tsx I'm not sure if the hook should be used directly in a functional component or if it is an alternative to the <ActionSheetProvider /> HOC

**Comment by superandrew** [comment]
I realized that I needed to embed with <ActionSheetProvider> also that component that used the component with the sheet. Is this by design? I thought embedding the entire App inside <ActionSheetProvider> would have been enough.

**Comment by bradbumbalough** [comment]
@superandrew can you post an example of what you had to do to get this to work? You should only need to wrap the top level component, and then use the hook at the component you need it. Did you try connecting the component in question instead of the hook?

**Comment by superandrew** [comment]
I had to embed the component up one level from my functional component to make it work. Generally speaking, I have on the application many components, most of them are class based, so with the connect they work. We started with hooks recently, so I hoped the main <ActionSheetProvider / > in app.tsx would have sufficed.

**Comment by bradbumbalough** [comment]
Any chance this comment helps you at all? https://github.com/expo/react-native-action-sheet/issues/154#issuecomment-575920842? this is for forwarding the props..

**Comment by superandrew** [comment]
Thanks, good suggestion. However I tried but it doesn't seem to work.

**Comment by superandrew** [comment]
Just to be more clear on which is my situation, I created a quick diagram:

![Diagram](https://user-images.githubusercontent.com/71364/90483542-26e0bb80-e135-11ea-9885-da886084abe7.png)

Basically with a declaration of <ActionSheetProvider > on the component that contains the component that uses the sheet, it works

**Comment by bradbumbalough** [comment]
@superandrew did you find anything more about this that could explain why it was not working? My gut is that there was a prop not being passed down or something.

**Comment by superandrew** [comment]
unfortunately no, I didn't. I'm sure there is an explanation, however I am forced to embed the component inside the tag to make it work on the functional component.

**Comment by yybot1** [comment]
I encountered a similar problem, and eventually I noticed that the problem is related to the "react-native-navigation" library I used. If you use any navigation libraries, then just wrap top-level component with <ActionSheetProvider /> may not work. 

For "react-native-navigation", I have to wrap each component separately using Navigation.registerComponent()
