### ISSUE TITLE
Enhance the usage

### ISSUE THREAD

**Issue by FlashLim** [expo/react-native-action-sheet#182]
Hi,

Thanks for the great library , it works completely fine without any issue. 
But I think there's something can be improve to make our life better, Is there any way to handle the button index?

If we are going dynamic action sheet, it will need a lot of extra code or effort to achieve it. 

Any idea? 

Again, thanks for the great library

**Comment by bradbumbalough** [comment]
Hi @FlashLim I'm not 100% sure I'm following... this implementation is a proxy to the [native iOS handler](https://reactnative.dev/docs/actionsheetios), and the Android is made to mirror that API. 

You could try something like this perhaps...
```js
const options = [{
  label: 'Press me',
  onPress: doSomething
}];

// logic to add or remove dynamic options

props.showActionSheetWithOptions({
  options: options.map(({label}) => label), 
}, index => { 
  if (options[index]) {
    options[index].onPress();
  }
});
```
This is not tested but just to give you an idea. You could even make a helper function that is reusable so you don't have to replicate this pattern.

**Comment by FlashLim** [comment]
That actually help a lot, guess I am thinking too much 😅

**Comment by bradbumbalough** [comment]
Awesome!
