### ISSUE TITLE
Can I use SVG elements as icons?

### ISSUE THREAD

**Issue by reinink** [expo/react-native-action-sheet#195]
Hey there! Thanks for this library.

I am wondering if it is possible to use SVG icons with this library? I use SVG graphics a lot in my React Native app (using [react-native-svg](https://github.com/react-native-svg/react-native-svg)), and it would be great to be able to pass SVG elements as the icons for the action sheet.

Something like this:

```jsx
showActionSheetWithOptions(
  {
    options: ['Call 555-666-7777', 'Message 555-666-7777', 'Copy', 'Cancel'],
    icons: [
      <Svg width="16" height="16" viewBox="0 0 20 20">
        <Path d="M2 3a1 1 0 011-1h2.153a1 1 0 01.986.836l.74 4.435a1 1 0 01-.54 1.06l-1.548.773a11.037 11.037 0 006.105 6.105l.774-1.548a1 1 0 011.059-.54l4.435.74a1 1 0 01.836.986V17a1 1 0 01-1 1h-2C7.82 18 2 12.18 2 5V3z" />
      </Svg>,
      <Svg width="16" height="16" viewBox="0 0 140 140">
        <Path d="M84.583 61.25h24.792a1.458 1.458 0 001.458-1.458V32.083a26.28 26.28 0 00-26.25-26.25H26.25A26.28 26.28 0 000 32.083v23.334a26.25 26.25 0 0026.25 26.25h2.917v20.416a2.917 2.917 0 005.11 1.92l19.11-21.835a1.44 1.44 0 011.096-.501h5.834a1.452 1.452 0 001.435-1.202A23.28 23.28 0 0184.583 61.25z" />
        <Path d="M140 84.583A14.583 14.583 0 00125.417 70H84.583A14.583 14.583 0 0070 84.583v17.5a14.583 14.583 0 0014.583 14.584h10.46l16.642 16.648a2.917 2.917 0 004.982-2.065v-14.583h8.75A14.583 14.583 0 00140 102.083z" />
      </Svg>,
      <Svg width="16" height="16" viewBox="0 0 20 20">
        <Path d="M9 2a2 2 0 00-2 2v8a2 2 0 002 2h6a2 2 0 002-2V6.414A2 2 0 0016.414 5L14 2.586A2 2 0 0012.586 2H9z" />
        <Path d="M3 8a2 2 0 012-2v10h8a2 2 0 01-2 2H5a2 2 0 01-2-2V8z" />
      </Svg>
    ],
  },
)
```

**Comment by bradbumbalough** [comment]
I'm guessing you've already tried this example code and it didn't work? All it's doing is checking whether to render out an image or not... https://github.com/expo/react-native-action-sheet/blob/master/src/ActionSheet/ActionGroup.tsx#L101. At the least you might be able to save the file as an `.svg` and require it in the array.

**Comment by reinink** [comment]
Hey Brad, thanks for the quick response.

Yes, I have tried the example code, but I couldn't get the icons to appear. If you think it should have worked, let me give it another try. Maybe there's something I'm missing.

**Comment by bradbumbalough** [comment]
@reinink any luck getting it to work?

**Comment by reinink** [comment]
Hey sorry @bradbyte...never got around to testing this again. Hopefully some day when I'm back into that project. 👍
