### ISSUE TITLE
Can I use this library on a project not using Expo ?

### ISSUE THREAD

**Issue by cini9** [expo/react-native-action-sheet#198]
Hi guys, I'm pretty new to React Native and I'm not 100% sure if this is this right place to ask this question, but here goes...

And I apologise in advance if this question is a bit stupid so feel free to mock me :D

Can I use this library in a project that does not use expo ? It seems to be the only one that allows me to have something similar to the native ActionSheetIOS component for IOS and something basic for Android. 

Thanks for your responses !

**Comment by ziyafenn** [comment]
@cini9 probably you have found it out yourself already, but yes, this library also works on non-expo projects.
