### ISSUE TITLE
[BUG] Closing action style sheet cause an invisible layer

### ISSUE THREAD

**Issue by MichaelGorski** [expo/react-native-action-sheet#205]
Hi guys,

I discovered a weird bug?
When I open the action sheet and close it, the lower half of the display becomes not clickable.
I have being testing some different screens and happens several times. I could fix some layers of other components to be clickable when I set an zIndex.

Using expo 40.1, android

**Comment by bradbyte** [comment]
Can you provide a screenshot, screencast, or reproducible sample code in an Expo snack? Thank you!

**Comment by MichaelGorski** [comment]
Actually it is not caused by action sheet. Sorry for that! Can be closed.
It is caused by Overlay. Different lib!
