### ISSUE TITLE
Is it possible to create separate section in the Action Sheet for various options?

### ISSUE THREAD

**Issue by ausshadu** [expo/react-native-action-sheet#207]
Something like this

![image](https://user-images.githubusercontent.com/7588667/112430604-62df9d00-8d64-11eb-9ae6-2273008d4178.png)

**Comment by ausshadu** [comment]
Hi team, is it possible to create a sub-section similar to this?

CC: @jdmunro @soh335 @brentvatne @skevy

**Comment by brentvatne** [comment]
the ios implementation of this library is built on top of [ActionSheetIOS](https://reactnative.dev/docs/actionsheetios) which does not support this type of ui as far as i know
