### ISSUE TITLE
How Can customize cancel button Container style 

### ISSUE THREAD

**Issue by edwards19900128** [expo/react-native-action-sheet#211]
I want separator the cancel item use customize style, like the below picture, 
Hey guys , This component has the cancelButtonContainerStyle props?
![image](https://user-images.githubusercontent.com/11594850/114550291-9a22d900-9c94-11eb-858f-d722bbb84832.png)

**Comment by bradbyte** [comment]
Hi @edwards19900128 this is possible, you just need to provide the `cancelButtonIndex` prop. https://reactnative.dev/docs/actionsheetios#showactionsheetwithoptions. If you want to customize that separately from the other options, that is currently not possible.
