### ISSUE TITLE
[Enhancement] Allow to use action-sheet Android on iOS

### ISSUE THREAD

**Issue by psyzz** [expo/react-native-action-sheet#212]
Hello, thanks for this library,

Would be great if we can add an option to use Android's action-sheet style on iOS to have a more consistent experience although this library is basically to mimic the two different action-sheets of each platform.

Regards

**Comment by bradbyte** [comment]
Can anyone else who wants this +1 the issue? Just trying to gauge interest. Thanks!

**Comment by bradbyte** [comment]
I have a release candidate for this feature at https://github.com/expo/react-native-action-sheet/pull/281.

Give it an install and let me know if you encounter any issues!
