### ISSUE TITLE
undefined in buttonIndex callback showActionSheetWithOptions 

### ISSUE THREAD

**Issue by pmgzo** [expo/react-native-action-sheet#222]
Hi,

I would like to open this issue because I had some trouble with my app.

```js
ActionSheet.showActionSheetWithOptions(
      {
        options,
      },
      (i) => {
        setSelectedKind(kinds[i]);
      }
    );
```
When my action sheet is displayed and I clicked on the return button of my emulator, the buttonIndex callback is triggered and I got parameter **i** as undefined that cause my app to crash.
I thought that this parameter type was of type number: [https://github.com/expo/react-native-action-sheet/blob/master/src/types.ts#L5](https://github.com/expo/react-native-action-sheet/blob/master/src/types.ts#L5)

I also considered this pr: [https://github.com/expo/react-native-action-sheet/pull/102](url), but I'm not sure to understand the point. Is it possible that this callback is not called if we click on the return button ? Are we obliged to put a cancel button on the action sheet to get the expected behavior ?

**Comment by bradbyte** [comment]
You should pass in a `cancelButtonIndex` or at least guard against an undefined `i` when calling `setSelectedKind`.

**Comment by pmgzo** [comment]
Ok but I find it pretty restrictive though maybe I missed the point is there any rationale ?

**Comment by pmgzo** [comment]
Thank you for you answer, I wanted to say that I received an undefined `i` in that callback which 
 is not the expected type precised here: https://github.com/expo/react-native-action-sheet/blob/master/src/types.ts#L5.
 I propose to specify that same variable to be either of type `number` or type `undefined`.

**Comment by bradbyte** [comment]
Thanks for the clarification!

**Comment by alamothe** [comment]
In what cases can it be undefined? If `cancelButtonIndex` is passed, is it guaranteed it won't be? Thanks!
