### ISSUE TITLE
Add support for disabledButtonIndices option

### ISSUE THREAD

**Issue by dawidchyrzynski** [expo/react-native-action-sheet#224]
Hi,

It would be nice to add support for `disabledButtonIndices` (array of indexes) that allows for disabling buttons in the action sheet.

**Comment by bradbyte** [comment]
@dawidchyrzynski do you mean `destructiveIndices` or actually disabled? I don't think iOS supports this, can you point me to a doc?

**Comment by dbarkleyjr** [comment]
There is an option called [disabledButtonIndices](https://reactnative.dev/docs/actionsheetios). This is preventing me from adopting at the moment.

**Comment by bradbyte** [comment]
Ah ok. Thank you for that.

**Comment by bradbyte** [comment]
This is only supported in RN 0.64 and so not part of the Expo packages yet. I can add the option in but it won't work for Expo users until (I think) Expo 43 drops.

**Comment by bradbyte** [comment]
@dbarkleyjr @dawidchyrzynski would you care to check out #246 and see if it will work for you?
