### ISSUE TITLE
Are we able to provide a callback to the cancel button?

### ISSUE THREAD

**Issue by youngrichard** [expo/react-native-action-sheet#263]
Since we do not define the action of the cancel button, is there any way we can supply a callback action to fire when the cancel button is pressed?

Thank you

**Comment by bradbyte** [comment]
@youngrichard what is the use case? It could be helpful when thinking of possible implementation. Thanks.

**Comment by youngrichard** [comment]
Our use case involves tracking user interactions, which we can do for the other buttons, but not cancel.

**Comment by bradbyte** [comment]
https://github.com/expo/react-native-action-sheet/blob/master/src/ActionSheet/index.tsx#L241-L242

I think this results in the `onPress` being called with the cancelIndex... is that not what you're seeing?
