### ISSUE TITLE
Styling cancel button

### ISSUE THREAD

**Issue by lewis221** [expo/react-native-action-sheet#272]
Is it able to change the colour of the cancel button?
I want to change the cancel button to red.
I follow to react-native ActionSheet https://reactnative.dev/docs/actionsheetios and see there is a props called cancelButtonTintColor. Is there a similar way in expo?
![image](https://user-images.githubusercontent.com/41378056/173283589-bb844768-7e3b-4f38-99e4-08f2baf99109.png)

**Comment by bradbyte** [comment]
This has been added in 3.14.0. Thanks!
