### ISSUE TITLE
Not compatible with Gradle 7

### ISSUE THREAD

**Issue by spsaucier** [expo/react-native-action-sheet#274]
This package is not compatible with Gradle 7 (included in recent React Native versions).

```
FAILURE: Build failed with an exception.

* Where:
Build file '~/project/node_modules/react-native-cross-actionsheet/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-cross-actionsheet'.
> Plugin with id 'maven' not found.
```

See https://docs.gradle.org/7.0/userguide/upgrading_version_6.html#removal_of_the_legacy_maven_plugin

**Comment by bradbyte** [comment]
Any chance this is for https://github.com/aelesia/react-native-cross-actionsheet?

**Comment by spsaucier** [comment]
It is indeed! Sorry about that.
