### ISSUE TITLE
[Android] change color of cancel button 

### ISSUE THREAD

**Issue by SymntxHomendra51** [expo/react-native-action-sheet#275]
I'm ok with the cancel button of ios but in android if I have a large list of options user cant tap outside of sheet to hide it. 
To highlight the cancel button I have to mention it in the destructive option list which removes it as a cancel button from the ios and makes it a simple destructive button.

![Screenshot_1663315349](https://user-images.githubusercontent.com/95675342/190588525-8b998748-81e7-4c84-9112-afee90d55ca1.png)

`  showActionSheetWithOptions(
              {
                options: opArr?.map(item => item.label),
                cancelButtonIndex: options?.length,
                destructiveButtonIndex: options?.length,
                destructiveColor: 'red',
              },
              index => {
                opArr[index].onPress()
              },
            )`

**Comment by bradbyte** [comment]
This has been added in 3.14.0. Thanks!
