### ISSUE TITLE
Two bugs with the new version 4.0.0

### ISSUE THREAD

**Issue by kovkev** [expo/react-native-action-sheet#282]
I am using react-native-gifted-chat and I encountered the following two bugs because of @expo/react-native-action-sheet@4.0.0. I don't get these issues with @expo/react-native-action-sheet@3.14.0.

Warning: Function components cannot be given refs. Attempts to access this ref will fail. Did you mean to use React.forwardRef()? #2295: https://github.com/FaridSafi/react-native-gifted-chat/issues/2295

Uncaught TypeError: Cannot read properties of undefined (reading 'showActionSheetWithOptions') #2294: https://github.com/FaridSafi/react-native-gifted-chat/issues/2294

**Comment by bradbyte** [comment]
Thank you! I’ll get right in that.

**Comment by bradbyte** [comment]
@kovkev have you verified all is well with 4.0.1? Thanks.

**Comment by kovkev** [comment]
Yes the issue is fixed at 4.0.1!
