### ISSUE TITLE
[edge-to-edge] behind the navigation bar in edge-to-edge

### ISSUE THREAD

**Issue by wcastand** [expo/react-native-action-sheet#332]
On android with edge-to-edge active, the ActionSheet falls behind the navigation bar and i can't see a way to add bottom inset to avoid it.

**Comment by nemoneph** [comment]
Hello @wcastand ,  I have the same problem.
How do you manage to resolve it ? 
Thx

**Comment by wcastand** [comment]
> Hello @wcastand ,  I have the same problem.
> How do you manage to resolve it ? 
> Thx

If I remember correctly I was missing the provider which was causing the issue but not sure anymore sorry

**Comment by nemoneph** [comment]
@wcastand thanks or the answer, I have the provider.
