### ISSUE TITLE
The component with connectActionSheet will fail hot loading.

### ISSUE THREAD

**Issue by lucaschai** [expo/react-native-action-sheet#40]
I noticed that the component with the `connectActionSheet` decorator will fail hot loading.
Have to do the manual reload for this component.

**Comment by thibault12** [comment]
I experience something similar!

**Comment by jordanmkoncz** [comment]
Having the same issue here, makes updating components that use `react-native-action-sheet` fairly tedious, having to do a full app restart every time you make a change.
