### ISSUE TITLE
this.props.showActionSheetWithOptions undefined?

### ISSUE THREAD

**Issue by booboothefool** [expo/react-native-action-sheet#41]
Where did I probably mess up?

this.props
![screen shot 2017-03-27 at 2 21 14 pm](https://cloud.githubusercontent.com/assets/13257645/24371428/bb8200f0-12f8-11e7-9a93-247c44d1bb19.png)

**Comment by booboothefool** [comment]
Had to wrap       <ActionSheetProvider>

**Comment by Sam1301** [comment]
+1 to that
