### ISSUE TITLE
Invalid name

### ISSUE THREAD

**Issue by nickkapoor** [expo/react-native-action-sheet#43]
When I try to install npm install @expo/react-native-action-sheet  I am getting this following error:

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "@expo/react-native-action-sheet"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10

npm ERR! Invalid name: "@expo/react-native-action-sheet"
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:

**Comment by peterpme** [comment]
Should be fixed with 1.0.2. Thanks!
