### ISSUE TITLE
BackHandler should fall back to BackAndroid

### ISSUE THREAD

**Issue by jjwon0** [expo/react-native-action-sheet#50]
Although `BackHandler` is now the standard, it is not present on older versions of `react-native`, so if you're using any `react-native` older than `0.44`, there is a bug. There are two possible fixes:

- Change the `react-native` version in `package.json` to only support `react-native >= 0.44`
- Import `BackHandler` and `BackAndroid`, and if `BackHandler` is undefined, use `BackAndroid` as the handler.

**Comment by jordanmkoncz** [comment]
Yep I ran into this same issue as I'm using `react-native` `0.41.2` currently.

**Comment by sibelius** [comment]
we recommend upgrading your react-native code base

we are already on RN50

@brentvatne you can close this as well
