### ISSUE TITLE
[Android]Scrolling issue in Actionsheet

### ISSUE THREAD

**Issue by saketkumar95** [expo/react-native-action-sheet#53]
If there are many options in the actionsheet , then we cannot get to choose the last options.
Scrolling is not possible in landscape mode.

**Comment by borisyankov** [comment]
To the maintainers:
Merging this PR https://github.com/expo/react-native-action-sheet/pull/30 solves this issue.

**Comment by peterpme** [comment]
#30 was merged. Thanks!
