### ISSUE TITLE
Receiving warning (cases chrome breakpoint) Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16

### ISSUE THREAD

**Issue by dchersey** [expo/react-native-action-sheet#58]
Originating from `ActionSheetProvider.js:6`

Running with dependencies
```
  "dependencies": {
    "@expo/react-native-action-sheet": "^1.0.0",
    "@expo/samples": "^2.0.2",
    "expo": "^20.0.0",
    "react": "16.0.0-alpha.12",
    "react-native": "https://github.com/expo/react-native/archive/sdk-20.0.0.tar.gz",
    "react-native-sentry": "^0.21.2",
    "react-navigation": "^1.0.0-beta.12",
    "react-redux": "^5.0.6",
    "redux": "^3.7.2",
    "redux-logger": "^3.0.6",
    "redux-persist": "^4.9.1"
  }
```

Please fix; this breaks my code every time the app reloads, unless I turn off breakpoints.

Thank you!

**Comment by evturn** [comment]
There is a pull request for this from a month ago that hasn't been merged.

https://github.com/expo/react-native-action-sheet/pull/56

This library is pretty great as it works for both iOS & Android so I hope there are plans to continue maintaining it.

**Comment by xcarpentier** [comment]
See #59

**Comment by sibelius** [comment]
@brentvatne we can close this as well
