### ISSUE TITLE
Not working in RN 0.50.3

### ISSUE THREAD

**Issue by justColbs** [expo/react-native-action-sheet#62]
The `@connectActionSheet` before the class declaration, just as it is in docs, throws an error when trying to build. I assume this is because of some changes in RN 0.50.3? Any help/guidance would be awesome! 

This is a brand new project, btw. 
React 16.0.0
RN 0.50.3

**Comment by sibelius** [comment]
you need to setup .babelrc correctly

**Comment by sibelius** [comment]
you need to setup .babelrc correctly

**Comment by brentvatne** [comment]
indeed the your babel config needs to support decorators. if it doesn't, do `export default connectActionSheet(WhateverComponent)`rather than exporting the component directly

**Comment by MayeuldP** [comment]
I m confused, what do you mean by setup .babelrc :/ ? I got the same error here...
Thanks for the help
