### ISSUE TITLE
Expo link not working: Old SDK version

### ISSUE THREAD

**Issue by brunolemos** [expo/react-native-action-sheet#65]
_BTW, I always wondered why [these expo pages](https://expo.io/@community/react-native-action-sheet-example) doesn't generate a snack link as well_

![img_1221](https://user-images.githubusercontent.com/619186/34003583-ca7b1d46-e0dc-11e7-9355-eb5f8c18af45.PNG)

**Comment by peterpme** [comment]
Updated to v24.

Thanks!

**Comment by wiktoriatomzik** [comment]
![image](https://user-images.githubusercontent.com/17315148/56904482-9c3aff80-6a9e-11e9-9e23-1746585feeb3.png)
How about updating it again? It doesn't work now.
