### ISSUE TITLE
Changes in ActionSheet.android.js were reverted

### ISSUE THREAD

**Issue by abbiecat** [expo/react-native-action-sheet#68]
After this PR was merged https://github.com/expo/react-native-action-sheet/commit/e73314d994bbff1355dbd5a2cdea469f3f7fa496#diff-3f3314f300451101b2c6e75447496621

The changes were (accidentally?) reverted by https://github.com/expo/react-native-action-sheet/commit/3c2a61de8e26a21defd26609806dd86a84ed6c78#diff-3f3314f300451101b2c6e75447496621

npm hasn't been updated with the prop-types change yet so I tried using:
`"@exponent/react-native-action-sheet": "github:expo/react-native-action-sheet",`

Which does work for iOS but still fails for Android

Using the work around:
`"@exponent/react-native-action-sheet": "github:xcarpentier/react-native-action-sheet",`

until the change to master is reverted

**Comment by jamesalways** [comment]
Thanks!

**Comment by gvillenave** [comment]
Any update on when this is going to be fixed and the NPM package updated?

**Comment by brunolemos** [comment]
This can be closed, but the npm package still needs a new release.

**Comment by peterpme** [comment]
Thanks!
