### ISSUE TITLE
Doesn't work when a Modal is open on Android

### ISSUE THREAD

**Issue by pietro909** [expo/react-native-action-sheet#73]
If I use `<Modal>` component from `react-native`, on Android the sheet is shown below the modal.

I can see it *after* I've closed the modal.

**Comment by mathieumg** [comment]
Having the same issue here!

**Comment by peterpme** [comment]
Hm, I believe modals will always go above everything (even Expo's debug menu).

Were you able to figure this out?

**Comment by pietro909** [comment]
>  I believe modals will always go above everything (even Expo's debug menu)
I understand, but how come it works on IOS?

Anyway: we solved this using the native one for IOS and [react-native-bottom-action-sheet](https://github.com/prscX/react-native-bottom-action-sheet) for Android :-)

**Comment by peterpme** [comment]
Perfect!

**Comment by pietro909** [comment]
@peterpme the fact that solved this one using a different package doesn't mean that this is not a problem anymore...

I think it should stay open until is either solved or the README states clearly that this "feature" is not among the requirements in my opinion.

**Comment by peterpme** [comment]
Hey @pietro909!

You're welcome to open a PR and add this to the README!

**Comment by Thomazella** [comment]
same problem

**Comment by szmarci** [comment]
same problem here as well

**Comment by peterpme** [comment]
@Thomazella @szmarci you're welcome to open up a PR! I've been out of town for App.js Conf & Reason Conf. Thank you!

**Comment by lmuntaner** [comment]
I guess there hasn't been any update regarding this issue...

Still waiting for PRs?
