### ISSUE TITLE
if I use "@connectActionSheet" , the project will crash and err : "SyntaxError"

### ISSUE THREAD

**Issue by TaoHenry** [expo/react-native-action-sheet#79]

**Comment by TaoHenry** [comment]
access actionSheet method as this.props.showActionSheetWithOptions and I received this err: 'undefined is not a function (near '...this.props.showActionSheetWithOptions...')"

**Comment by 2207345508** [comment]
I have this problem too.

**Comment by adrianByv** [comment]
Hi. I was wrapping my `current` component/screen with <ActionSheetProvider /> and getting the same error.

Like is said in [README](https://github.com/expo/react-native-action-sheet#a-basic-actionsheet-setup) It must be wrapped to the `top-level` component.

I changed it to my `top-level` component and it worked.
App.js:
```javascript
export default class App extends React.Component {
  render() {
    return (
      <ActionSheetProvider>
        <TabBar />
      </ActionSheetProvider>
    )
  }
}
```

**Comment by mfxuus** [comment]
I've wrapped the `<ActionSheetProvider>` in the top-level component but still no luck... same SyntaxError. Not sure what I'm doing wrong.

**Comment by mitchellbutler** [comment]
The `@` symbol is called a decorator (check out [this article](https://www.sitepoint.com/javascript-decorators-what-they-are/) for reference). Your environment may not implement them, especially since they're still part of a proposal that's subject to change. **For now you can ignore the decorator shorthand like this:**

```js
import React, { Component } from 'react';
import { connectActionSheet } from '@expo/react-native-action-sheet';

class TheClassYouWantToConnect extends Component {
  // ...
}

export default connectActionSheet(TheClassYouWantToConnect);
```

**Comment by peterpme** [comment]
Thanks @mitchellbutler. Closing this
