### ISSUE TITLE
Release v1.0.3?

### ISSUE THREAD

**Issue by jesperlndk** [expo/react-native-action-sheet#80]
Any plans on doing a new release? I would love to have the UI changes from https://github.com/expo/react-native-action-sheet/pull/52 in my project.

Thanks a lot!

**Comment by giautm** [comment]
Yeah, look like #52 not released yet. So I have to install from git. :(
```
yarn add git+https://github.com/expo/react-native-action-sheet.git
```

**Comment by peterpme** [comment]
1.1.0 is being released today. Thanks!
