### ISSUE TITLE
Why no static API?

### ISSUE THREAD

**Issue by DylanVann** [expo/react-native-action-sheet#82]
If using something like `redux-saga` or `redux-observable` then I would think of an action sheet as a type of side effect that should be handled outside of a component. 

There's currently no way to present an action sheet outside of a component though, so one couldn't be shown from a saga.

I could look into it and maybe find some way to create a static API.

As an alternative or addition to this a more declarative component based API might also be nicer

**Comment by HugoHeneault** [comment]
This *might* be useful, even if it's not really static? https://github.com/pietro909/react-native-action-sheet/commit/36062fcacf0089e3619ca577332ea7fd1f246ab4

**Comment by DylanVann** [comment]
It could maybe be done by having `componentDidMount` do something like `ActionSheet.SharedActionSheet = this` (where `ActionSheet` is just an exported global object), then anywhere else in the app using `ActionSheet.SharedActionSheet.showActionSheetWithOptions({})`.

**Comment by peterpme** [comment]
There's no static API b/c of the Provider / Consumer pattern. If I'm overlooking something, please feel free to re-open @DylanVann. Thank you!
