### ISSUE TITLE
Use without decorators?

### ISSUE THREAD

**Issue by maximmcnair** [expo/react-native-action-sheet#87]
It it possible to use this without decorators? There seems to be a lot of issue with RN 56's use of babel 7 and decorators.

**Comment by peterpme** [comment]
@maximmcnair yes, absolutely.

Instead of doing:

```jsx
@connectActionSheet
export default class MyComponent ...
```

Consider doing

```jsx
class MyComponent ...

export default connectActionSheet(MyComponent)
```

Thanks!
