### ISSUE TITLE
Is AlertIOS.prompt and android equivalent supported?

### ISSUE THREAD

**Issue by rturk** [expo/react-native-action-sheet#9]
Hi Exponent team,

Is possible to use prompt with this package as:

```
AlertIOS.prompt(
  'Enter password',
  'Enter your password to claim your $1.5B in lottery winnings',
  [
    {text: 'Cancel', onPress: () => console.log('Cancel Pressed'), style: 'cancel'},
    {text: 'OK', onPress: password => console.log('OK Pressed, password: ' + password)},
  ],
  'secure-text'
);

```

As described in: (https://facebook.github.io/react-native/docs/alertios.html) ?

**Comment by jesseruder** [comment]
Hi @rturk. That's not supported right now. Do you have an idea of how that should work on Android?

**Comment by sibeliusseraphini** [comment]
@rturk you can use this cross platform component - https://github.com/jaysoo/react-native-prompt
