### ISSUE TITLE
New home for ActionSheetIOS ?

### ISSUE THREAD

**Issue by maxaggedon** [expo/react-native-action-sheet#90]
The react native team is looking to remove some RN components from the main repo (cf https://github.com/react-native-community/discussions-and-proposals/issues/6). `ActionSheetIOS` is one of them.

As I proposed [some changes](https://github.com/react-native-community/discussions-and-proposals/issues/10) to its API it was suggested it should be extracted first, and this repo came up as the best candidate. Would be great to have the maintainers' opinion on this !

**Comment by peterpme** [comment]
Sure! Great idea @maxaggedon

**Comment by maxaggedon** [comment]
@peterpme ok I will try to find some time to open a proposal for this then. I will keep you updated and close this issue once it's done!

**Comment by peterpme** [comment]
Closing until we re-start discussion
