### ISSUE TITLE
Andriod Styles

### ISSUE THREAD

**Issue by BrodaNoel** [expo/react-native-action-sheet#93]
Hi everyone!
I was testing it on Android and seems like `react-native-action-sheet` is using the iOS styles in Android. From a UX point of view, this is not correct.

If you [search "android option menu" in Google](https://www.google.com.ar/search?q=android+option+menu&source=lnms&tbm=isch&sa=X&ved=0ahUKEwi_z7vf9eXeAhWHqZAKHXBcC6QQ_AUIDigB&biw=1440&bih=798), you'll see that the Android style should be a dropdown like [this](https://i.stack.imgur.com/xFlzp.png) or [this](https://www.androidpolice.com/wp-content/uploads/2017/10/nexus2cee_Screenshot_20171030-214935-1-668x1188.png)

Do you have some plans to implement it?

PS.: I'm not an Android user. So, I'm not 100% sure if my proposal is actually the correct implementation.

**Comment by peterpme** [comment]
@BrodaNoel see latest master. Thanks
